name: tests

on:
  pull_request:
    branches:
    - main
    - master
    - dev
    - rc

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-and-linting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run linter (ESLint)
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
